title: MarkCraft
description: MarkCraft is a Minecraft Bedrock SMP ran by SMT AdriMark and Mark. Apply today and become one of the best.
baseurl: "" 
url: "https://markcraft.org" 

markdown: kramdown
highlighter: rouge

plugins: []

collections:
  players:
    output: true
    permalink: /players/:name/